[package]
name = "broom-runtime"
version = "0.1.0"
authors = ["Pauli Jaakkola <pauli.jaakkola@iki.fi>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true

[dependencies]
nix = "0.16.1"
lazy_static = "1.4.0"

