name:                broom
version:             0.1.0.0
github:              "nilern/broom"
license:             BSD3
author:              "Pauli Jaakkola"
maintainer:          "pauli.jaakkola@iki.fi"
copyright:           "2018 Pauli Jaakkola"

extra-source-files:
- ../README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nilern/broom#readme>

default-extensions:
- TupleSections
- LambdaCase
- OverloadedStrings
- NamedFieldPuns
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- DeriveDataTypeable
- MultiParamTypeClasses
- FlexibleInstances
- FlexibleContexts
- ScopedTypeVariables
- RankNTypes
- MonoLocalBinds

dependencies:
- base
- array
- hashable
- text
- unordered-containers
- hashtables
- convertible
- extensible-effects
- uniplate
- prettyprinter
- optparse-applicative

data-files: ../runtime/runtime.js

library:
  source-dirs: src
  build-tools: [alex, happy]
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall

executables:
  broomc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - broom
